USE challenge;

CREATE TABLE C_CONTAS_PAGAR 
(
	CONTAS_PAGAR_ID BIGINT IDENTITY (1, 1) NOT NULL,
	ID_FORNECEDOR BIGINT NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PRORROGACAO DATE,
	VALOR NUMERIC(18, 6) NOT NULL,
	ACRESCIMO NUMERIC(18, 6),
	DESCONTO NUMERIC(18, 6),
	CONSTRAINT PK_CONTAS_PAGAR PRIMARY KEY (CONTAS_PAGAR_ID),
	CONSTRAINT FK_FORNECEDOR_CONTAS_PAGAR FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES C_PESSOAS (PESSOA_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

