USE challenge;

CREATE TABLE C_CONTAS_PAGAS 
(
	CONTAS_PAGAS_ID BIGINT IDENTITY (1, 1) NOT NULL,
	ID_FORNECEDOR BIGINT NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PAGAMENTO DATE NOT NULL,
	VALOR NUMERIC(18, 6) NOT NULL,
	ACRESCIMO NUMERIC(18, 6),
	DESCONTO NUMERIC(18, 6),
	CONSTRAINT PK_CONTAS_PAGAS PRIMARY KEY (CONTAS_PAGAS_ID),
	CONSTRAINT FK_FORNECEDOR_CONTAS_PAGAS FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES C_PESSOAS (PESSOA_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
